apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: helloall
  description: helloall.com
  annotations:
    github.com/project-slug: vinnie-jog-on/helloall
    jira/project-key: ENISDT
    sonarqube.org/project-key: vinnie-jog-on-helloall

  links:
    - url: https://tracker.intive.com/jira/secure/RapidBoard.jspa
      title: backlog
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: user:guests
